name: Veille Hebdomadaire Google Chat
on:
  schedule:
    - cron: '0 8 * * 1' # Tous les lundis à 8h UTC (9h heure française)
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  post-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install rss-url-parser
        
      - name: Run script
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
            npm install rss-parser
            node veille.js
